/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package opencv_test;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfPoint;
import org.opencv.core.Point;
import org.opencv.core.Rect;
import org.opencv.core.Scalar;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.Imgproc;
import org.opencv.videoio.VideoCapture;


public class App {
    // Load the native code library for OpenCV from the gradle lib.
    static{ nu.pattern.OpenCV.loadLocally(); }

    // Define the area of the captured picture to look at.
    private static Point TOPLEFT_ANCHOR_POINT = new Point(250,200);
    private static Point BOTTOMRIGHT_ANCHOR_POINT = new Point(300,275);

    /**
     * Main program function, execution starts here.
     * @param args string array of command line arguments. Not used.
     */
    public static void main(String[] args) {
        System.out.println("Welcome to OpenCV " + Core.VERSION);

        // create image capture for zeroth web cam.
        //VideoCapture vc = new VideoCapture(0);
        Mat image = Imgcodecs.imread("C:/Users/matth/OneDrive/Documents/Robotics/opencv_test/IMG_8940.jpg" ); 
        //writeImage(image, "original");

        // transform the image data into yCrCb color format.
        Mat yCrCb = new Mat();
        Imgproc.cvtColor(image, yCrCb, Imgproc.COLOR_BGR2YCrCb);

        // Extract the blue channel and save for reference.
        Mat blue = new Mat();
        Core.extractChannel(yCrCb, blue, 1);

        // Extract the red channel and save for reference.
        Mat red = new Mat();
        Core.extractChannel(yCrCb, red, 2);

        // Extract the intensity channel and save for reference.
        Mat intensity = new Mat();
        Core.extractChannel(yCrCb, intensity, 0);

        // grab the average value for the blue and red channels, and print out to console.
        int avg1 = (int) Core.mean(blue).val[0];
        int avg2 = (int) Core.mean(red).val[0];

        System.out.println("blueavg:"+avg1 + " redavg:" + avg2);

        //writeImage(red, "blue");

        Mat hsv = new Mat();

        Imgproc.cvtColor(image, hsv, Imgproc.COLOR_BGR2HSV);

        Mat mask = new Mat();


        Scalar lower = new Scalar(0, 150, 200);
        Scalar upper = new Scalar(55, 255, 255);

        Core.inRange(hsv, lower, upper, mask);

        writeImage(mask, "yellow");
        
        Mat threshold = new Mat();
        Imgproc.threshold(hsv, threshold,  127, 255, Imgproc.THRESH_BINARY);

        
        

        List<MatOfPoint> contours = new ArrayList<MatOfPoint>();
        Imgproc.findContours(mask, contours, threshold, Imgproc.RETR_EXTERNAL, Imgproc.CHAIN_APPROX_NONE);
        System.out.println("Found " + contours.size() + " Contours");
        writeImage(threshold, "thresh");
        for(int i = 0; i < contours.size(); i++)
        {
            System.out.println("contour " + i + " width " + contours.get(i).width());
        }
    }

    /**
     * Writes out the image to a file in a specific directory.
     * 
     * File is named with current date/time stamp plus a provided label.
     * 
     * @param image The Mat of the image to print
     * @param label The label to include in the filename.
     */
    public static void writeImage(Mat image, String label)
    {
        // Generate name
        String name = "C:/Users/matth/OneDrive/Documents/Robotics/images/"  + new SimpleDateFormat( 
            "yyyy-MM-dd-hh-mm-ss") 
            .format(new Date( )) + label + ".jpg";

        // note filename to output
        System.out.println("Saving capture to " + name);

        // Write to file 
        Imgcodecs.imwrite(name, image); 
    }
}
